config/routes.rb
Rails.application.routes.draw do
  resources :tv_channels do
    get 'favroite'
  end
  root 'tv_channels#index'

  post 'tv_channels/search', to: "tv_channels#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :tv_show

end

app/models/tv_channel.rb
class TvChannel < ApplicationRecord

  validates :name, presence: true
  has_many :tv_shows, dependent: :delete_all
end

app/models/tv_show.rb
class TvShow < ApplicationRecord

  validates :name, :timing, presence: true
  belongs_to :tv_channel
end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, :last_name, presence: true

  has_many :favorites

  def favorite_show(show_id)
    self.favorites.pluck(:tv_show_id).include?(show_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tv_channels_controller.rb
class TvChannelsController < ApplicationController
  before_action :set_tv_channel, only: [:show, :edit, :update, :destroy]

  # GET /tv_channels
  def index
    @tv_shows = TvShow.includes(:tv_channel).order(created_at: :asc)
  end

  def favroite
    respond_to do |format|
      tv_show = TvShow.find_by(id: params[:show_id])
      format.js { render :js => "window.location.href = '/tv_channels'" } if tv_show.blank?
      #Set current user id.
      #for now I am mapping default user

      @current_user = User.first
      favorite = Favorite.new(user: @current_user, tv_show_id: tv_show.id)

      if favorite.save
        format.js { render :js => "window.location.href = '/tv_channels'" }

      else
        format.js { render :js => "window.location.href = '/tv_channels'" }
      end
    end
  end

  def search
    if params[:name].present?
      tv_channels = TvChannel.where('name LIKE ?', "%#{params[:name].capitalize}%")
      @tv_shows = TvShow.where(tv_channel_id: tv_channels.pluck(:id))
      @tv_shows = TvShow.where('name LIKE ?', "%#{params[:name].capitalize}%") if @tv_shows.blank?
    else
      @tv_shows = TvShow.includes(:tv_channel).order(created_at: :asc)
    end

    if request.xhr?
      render :json => {
        html: render_to_string(partial: 'tv_channels/form')
      }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_channel
      @tv_channel = TvChannel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tv_channel_params
      params.fetch(:tv_channel, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_channels_helper.rb
module TvChannelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Channel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tv_channels/_form.html.erb
<table>
  <thead>
    <tr>
      <th>Show Name</th>
      <th>Channel</th>
      <th>Timing</th>
      <th>Favorite</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tv_shows.each do |tv_show| %>
      <tr colspan='3'>
        <td><%= tv_show.name %></td>
        <td><%= tv_show.tv_channel.name %></td>
        <td><%= tv_show.timing %></td>
        <td><%= User.first.favorite_show(tv_show.id) ? 'Yes' : 'No' %></td>
        <td><%= link_to 'Favorite', tv_channel_favroite_path(tv_channel_id: tv_show.tv_channel.id, show_id: tv_show.id), remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tv_channels/edit.html.erb
<h1>Editing Tv Channel</h1>

<%= render 'form', tv_channel: @tv_channel %>

<%= link_to 'Show', @tv_channel %> |
<%= link_to 'Back', tv_channels_path %>

app/views/tv_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tv Channels</h1>
<%= text_field_tag(:search, '', placeholder: 'Enter Channel name or Show name') %>

<div id="channel-list">
  <%= render('form') %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#search').keyup(function(){
      var value = $(this).val();
      search(value)
    })

    function search(data){
      $.ajax({
        url: '/tv_channels/search',
        method: 'post',
        data: {name: data},

        success: function(response){
          $('#channel-list').html(response.html)
        }
      })
    }
  })

</script>

app/views/tv_channels/new.html.erb
<h1>New Tv Channel</h1>

<%= render 'form', tv_channel: @tv_channel %>

<%= link_to 'Back', tv_channels_path %>

app/views/tv_channels/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tv_channel_path(@tv_channel) %> |
<%= link_to 'Back', tv_channels_path %>